// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AiTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ai() {
    Scanner sc = new Scanner(new File("email.csv"));  
          sc.useDelimiter(",");    
          while (sc.hasNext())  
          {  
          
          driver.get("https://mail.google.com/mail/u/0/#inbox");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".T-I-KE")).click();
    driver.findElement(By.id(":bk")).click();
    driver.findElement(By.id(":bk")).sendKeys(sc.next());
    driver.findElement(By.id(":b2")).click();
    driver.findElement(By.id(":b2")).sendKeys("Happy Birthday");
    driver.findElement(By.id(":c7")).click();
    {
      WebElement element = driver.findElement(By.id(":c7"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'Happy Birthday to you'}", element);
    }
    driver.findElement(By.id(":as")).click();
            
          }   
          sc.close(); 
    
  }
}
